// This file is auto-generated by manage-i18n.js
// Do not edit this file directly

export interface MessageSchema {
  aiConfig: {
    claude: {
      assistantPrefill: {
        description: string;
        label: string;
      };
      useSysPrompt: {
        description: string;
        label: string;
      };
    };
    contextSize: {
      label: string;
      unlocked: string;
      unlockedTooltip: string;
    };
    docsLinkTooltip: string;
    freqPenalty: {
      label: string;
    };
    google: {
      useSysPrompt: {
        description: string;
        label: string;
      };
    };
    koboldcpp: {
      bannedTokens: string;
      dryAllowedLength: string;
      dryBase: string;
      dryMultiplier: string;
      dryPenaltyLastN: string;
      drySequenceBreakers: string;
      dynatempExponent: string;
      dynatempRange: string;
      grammar: string;
      grammarRetainState: string;
      groups: {
        basic: string;
        dry: string;
        dynatemp: string;
        grammar: string;
        mirostat: string;
        tfs: string;
        xtc: string;
      };
      header: string;
      mirostat: {
        disabled: string;
        label: string;
        v1: string;
        v2: string;
      };
      mirostatEta: string;
      mirostatTau: string;
      nsigma: string;
      repPenRange: string;
      samplerOrder: string;
      smoothingFactor: string;
      tfs: string;
      typical: string;
      xtcProbability: string;
      xtcThreshold: string;
    };
    manualInputNote: string;
    maxResponseLength: {
      label: string;
    };
    minP: {
      label: string;
    };
    ollama: {
      groups: {
        advanced: string;
      };
      header: string;
      numBatch: string;
      numKeep: string;
      repeatLastN: string;
      tfsZ: string;
      typicalP: string;
    };
    presPenalty: {
      label: string;
    };
    presets: {
      delete: string;
      deletePopupContent: string;
      errors: {
        deleteDefault: string;
        exportNotFound: string;
        importInvalid: string;
        migrateFailed: string;
        noExportSelected: string;
        noPresetName: string;
        renameDefault: string;
      };
      export: string;
      import: string;
      messages: {
        migrateSuccess: string;
      };
      newName: string;
      rename: string;
      renamePopupTitle: string;
      sampler: {
        label: string;
      };
      saveAs: string;
      update: string;
    };
    promptManager: {
      addFromLibrary: string;
      content: string;
      description: string;
      globalPrompts: string;
      label: string;
      markerHint: string;
      newPrompt: string;
      noPrompts: string;
      role: string;
      selectFromLibrary: string;
    };
    promptsTitle: string;
    reasoningEffort: {
      descriptionClaude: string;
      descriptionGoogle: string;
      descriptionOpenAI: string;
      label: string;
      options: {
        auto: string;
        high: string;
        low: string;
        maximum: string;
        medium: string;
        minimum: string;
      };
      tooltip: string;
    };
    repPenalty: {
      label: string;
    };
    showThoughts: {
      description: string;
      label: string;
    };
    streaming: {
      description: string;
      label: string;
    };
    tabConnections: string;
    tabPrompts: string;
    tabSampler: string;
    temperature: {
      label: string;
    };
    topA: {
      label: string;
    };
    topK: {
      label: string;
    };
    topP: {
      label: string;
    };
    topPMinP: string;
  };
  api: {
    connectFailed: string;
    connectSuccess: string;
    status: {
      bypassed: string;
      connecting: string;
      noConnection: string;
      notConnected: string;
      valid: string;
    };
  };
  apiConnections: {
    ai21Key: string;
    ai21Model: string;
    aimlapiKey: string;
    aimlapiModel: string;
    azureApiVersion: string;
    azureBaseUrl: string;
    azureDeploymentName: string;
    azureKey: string;
    azureModel: string;
    claudeKey: string;
    claudeModel: string;
    cohereKey: string;
    cohereModel: string;
    cometapiKey: string;
    cometapiModel: string;
    connect: string;
    connecting: string;
    customKey: string;
    customModel: string;
    customProxy: {
      createProfile: string;
      deleteProfile: string;
      deleteProfileContent: string;
      deleteProfileTitle: string;
      password: string;
      passwordPlaceholder: string;
      renameProfile: string;
      saveProfile: string;
      title: string;
      url: string;
      urlPlaceholder: string;
    };
    customUrl: string;
    deepseekKey: string;
    deepseekModel: string;
    electronhubKey: string;
    electronhubModel: string;
    fireworksKey: string;
    fireworksModel: string;
    formatter: string;
    googleKey: string;
    googleModel: string;
    groqKey: string;
    groqModel: string;
    instruct: {
      create: string;
      delete: string;
      deleteContent: string;
      deleteTitle: string;
      edit: string;
      export: string;
      import: string;
      title: string;
    };
    keyPrivacy: string;
    koboldModel: string;
    koboldUrl: string;
    manageKeys: string;
    middleout: {
      auto: string;
      off: string;
      on: string;
    };
    mistralaiKey: string;
    mistralaiModel: string;
    moonshotKey: string;
    moonshotModel: string;
    nanogptKey: string;
    nanogptModel: string;
    ollamaModel: string;
    ollamaUrl: string;
    openaiKey: string;
    openaiModel: string;
    openrouterAllowFallbacks: string;
    openrouterFallbackProviders: string;
    openrouterKey: string;
    openrouterMiddleout: string;
    openrouterModel: string;
    openrouterOptions: string;
    openrouterUseFallback: string;
    openrouterWebsite: string;
    perplexityKey: string;
    perplexityModel: string;
    pollinationsModel: string;
    postProcessing: {
      description: string;
      label: string;
      noTools: string;
      prompts: {
        merge: string;
        merge_tools: string;
        none: string;
        semi: string;
        semi_tools: string;
        single: string;
        strict: string;
        strict_tools: string;
      };
      tooltip: string;
      withTools: string;
    };
    profile: string;
    profileManagement: {
      create: string;
      createPopupTitle: string;
      delete: string;
      deletePopupContent: string;
      errors: {
        deleteNone: string;
        nameExists: string;
        noSelection: string;
        renameNone: string;
      };
      export: string;
      fieldsToInclude: string;
      import: string;
      none: string;
      profileName: string;
      rename: string;
      renamePopupTitle: string;
    };
    provider: string;
    providers: {
      ai21: string;
      aimlapi: string;
      azure_openai: string;
      claude: string;
      cohere: string;
      custom: string;
      deepseek: string;
      electronhub: string;
      fireworks: string;
      groq: string;
      koboldcpp: string;
      makersuite: string;
      mistralai: string;
      moonshot: string;
      nanogpt: string;
      ollama: string;
      openai: string;
      openrouter: string;
      perplexity: string;
      pollinations: string;
      vertexai: string;
      xai: string;
      zai: string;
    };
    tokenizer: string;
    tokenizers: {
      auto: string;
      claude: string;
      commanda: string;
      commandr: string;
      deepseek: string;
      gemma: string;
      gpt2: string;
      gpt35: string;
      gpt4o: string;
      jamba: string;
      llama: string;
      llama3: string;
      mistral: string;
      nemo: string;
      none: string;
      qwen2: string;
      yi: string;
    };
    vertexaiKey: string;
    vertexaiModel: string;
    vertexaiProjectId: string;
    vertexaiRegion: string;
    xaiModel: string;
    xapiKey: string;
    zaiEndpoint: string;
    zaiKey: string;
    zaiModel: string;
  };
  backgrounds: {
    actions: {
      delete: string;
      lock: string;
      rename: string;
      unlock: string;
    };
    add: string;
    autoSelect: string;
    autoSelectTooltip: string;
    confirmDelete: string;
    errors: {
      delete: string;
      fetch: string;
      noChatLock: string;
      rename: string;
      upload: string;
    };
    fitting: string;
    fittingOptions: {
      center: string;
      classic: string;
      contain: string;
      cover: string;
      stretch: string;
    };
    renameTitle: string;
    searchPlaceholder: string;
    systemBackgrounds: string;
    zoomIn: string;
    zoomOut: string;
  };
  character: {
    create: {
      error: string;
    };
    delete: {
      confirmMessage: string;
      confirmTitle: string;
      deleteChats: string;
      error: string;
    };
    duplicate: {
      error: string;
    };
    export: {
      error: string;
    };
    fetch: {
      overflowWarning: string;
    };
    import: {
      abortedMessage: string;
      error: string;
      errorMessage: string;
      tagsImported: string;
      tagsImportedMessage: string;
      unsupportedType: string;
    };
    save: {
      error: string;
    };
    tokenWarning: string;
    updateImage: {
      error: string;
    };
  };
  characterEditor: {
    advanced: {
      characterNote: string;
      characterNotePlaceholder: string;
      characterVersion: string;
      characterVersionPlaceholder: string;
      createdBy: string;
      createdByPlaceholder: string;
      creatorNotes: string;
      creatorNotesPlaceholder: string;
      depth: string;
      dialogueExamples: string;
      dialogueExamplesPlaceholder: string;
      editingTitle: string;
      metadata: string;
      metadataHint: string;
      metadataOptional: string;
      personality: string;
      personalityPlaceholder: string;
      postHistoryInstructions: string;
      postHistoryInstructionsPlaceholder: string;
      promptOverrides: string;
      role: string;
      roles: {
        assistant: string;
        system: string;
        user: string;
      };
      scenario: string;
      scenarioPlaceholder: string;
      tagsToEmbed: string;
      tagsToEmbedPlaceholder: string;
      talkativeness: string;
      talkativenessChatty: string;
      talkativenessHint: string;
      talkativenessNormal: string;
      talkativenessShy: string;
    };
    alternateGreetings: {
      empty: string;
      label: string;
      placeholder: string;
      swapTooltip: string;
      title: string;
    };
    avatar: string;
    creatorNotes: string;
    delete: string;
    description: string;
    descriptionPlaceholder: string;
    detailsHidden: string;
    duplicate: string;
    embeddedLorebook: string;
    export: string;
    exportAsJson: string;
    exportAsPng: string;
    favorite: string;
    firstMessage: string;
    firstMessagePlaceholder: string;
    more: string;
    moreOptions: {
      convertToPersona: string;
      importCardLore: string;
      rename: string;
    };
    namePlaceholder: string;
    noCreatorNotes: string;
    openLastChat: string;
    searchTags: string;
    startNewChat: string;
    stats: {
      title: string;
    };
    toggleSpoiler: string;
    tokenCounts: {
      permanent: string;
      title: string;
      total: string;
    };
    validation: {
      avatarRequired: string;
      nameRequired: string;
    };
  };
  characterPanel: {
    createNew: string;
    editor: {
      placeholderButton: string;
      placeholderText: string;
      placeholderTitle: string;
    };
    importFile: string;
    searchPlaceholder: string;
    searchToggle: string;
    sorting: {
      favorites: string;
      nameAsc: string;
      nameDesc: string;
      newest: string;
      oldest: string;
      title: string;
    };
  };
  chat: {
    abort: string;
    buttons: {
      addReasoning: string;
      confirmEdit: string;
      copyMessage: string;
      deleteMessage: string;
      itemization: string;
      moveDown: string;
      moveUp: string;
      swipeLeft: string;
      swipeRight: string;
    };
    copy: {
      error: string;
    };
    createError: string;
    delete: {
      confirmBulkContent: string;
      confirmBulkTitle: string;
      confirmMessage: string;
      confirmSwipeMessage: string;
      confirmTitle: string;
      deleteMessage: string;
      deleteSwipe: string;
      lastSwipeError: string;
      plusOne: string;
    };
    emptyLog: string;
    generate: {
      errorFallback: string;
      noModelError: string;
      noPersonaError: string;
      noPrompts: string;
      noSpeaker: string;
      postProcessError: string;
    };
    groupChat: string;
    inputPlaceholder: string;
    itemization: {
      apiModel: string;
      bias: string;
      chatHistory: string;
      copy: string;
      description: string;
      disclaimer: string;
      examples: string;
      extensions: string;
      maxContext: string;
      persona: string;
      personality: string;
      preset: string;
      scenario: string;
      showRaw: string;
      showWorldInfo: string;
      systemInfo: string;
      title: string;
      tokenizer: string;
      totalTokens: string;
      worldInfo: string;
    };
    loadError: string;
    loadMoreMessages: string;
    options: string;
    optionsMenu: {
      continue: string;
      generate: string;
      manageChats: string;
      regenerate: string;
      selectMessages: string;
    };
    reasoning: {
      title: string;
    };
    selection: {
      modeFree: string;
      modeRange: string;
    };
    send: string;
    typingIndicator: string;
  };
  chatManagement: {
    actions: {
      delete: string;
      export: string;
      import: string;
      rename: string;
    };
    chatLorebooks: string;
    connectionProfile: string;
    createPrompt: string;
    deleteConfirmContent: string;
    deleteConfirmTitle: string;
    deleteSelectedConfirmContent: string;
    errors: {
      create: string;
      delete: string;
      export: string;
      noActiveChat: string;
      noMessagesToExport: string;
      rename: string;
    };
    import: {
      error: string;
      success: string;
    };
    newChat: string;
    noChatsFound: string;
    noRecentChats: string;
    renamePrompt: string;
    scenarioOverride: string;
    scenarioOverridePlaceholder: string;
    selectLorebooks: string;
    tabs: {
      chats: string;
      config: string;
      group: string;
    };
  };
  common: {
    activate: string;
    add: string;
    by: string;
    cancel: string;
    chat: string;
    close: string;
    confirm: string;
    confirmDelete: string;
    create: string;
    delete: string;
    dragToReorder: string;
    edit: string;
    expandedEditor: string;
    export: string;
    global: string;
    import: string;
    loading: string;
    messages: string;
    name: string;
    new: string;
    no: string;
    noResults: string;
    none: string;
    of: string;
    ok: string;
    refresh: string;
    remove: string;
    rename: string;
    reset: string;
    resetToDefaults: string;
    save: string;
    search: string;
    seconds: string;
    select: string;
    selectAll: string;
    selected: string;
    text: string;
    toggle: string;
    tokens: string;
    yes: string;
  };
  errors: {
    csrfToken: string;
  };
  extensions: {
    install: string;
    installPopupNotImplemented: string;
    manage: string;
    managePopupNotImplemented: string;
    notifyUpdates: string;
    placeholder: {
      text: string;
      title: string;
    };
  };
  extensionsBuiltin: {
    chatBranching: {
      branchButtonTitle: string;
      branchCreationFailed: string;
      branchName: string;
      branchPointTitle: string;
      branchTreeTitle: string;
      chatTreeTitle: string;
      createdTitle: string;
      loadChatFailed: string;
      noChatLoaded: string;
      rootChatTitle: string;
      rootLabel: string;
      totalMessagesTitle: string;
    };
    chatTranslation: {
      autoMode: {
        both: string;
        inputs: string;
        label: string;
        none: string;
        responses: string;
      };
      connectionProfile: string;
      connectionProfileHint: string;
      promptHint: string;
      promptTemplate: string;
      sourceLang: string;
      targetLang: string;
    };
    rerollContinue: {
      buildPromptFailed: string;
      buttonLabel: string;
      contextChanged: string;
      divergenceError: string;
      error: string;
      impersonateButtonLabel: string;
      impersonateDisabled: string;
      impersonating: string;
      impersonationFailed: string;
      noConnectionProfile: string;
      noPersona: string;
      noSnapshot: string;
      rerollDisabled: string;
      reverting: string;
      settings: {
        connectionProfileDesc: string;
        connectionProfileLabel: string;
        impersonateEnabled: string;
        impersonateTitle: string;
        promptDesc: string;
        promptLabel: string;
        rerollEnabled: string;
        reset: string;
      };
      swipeError: string;
    };
    undo: {
      discardLabel: string;
      discardTitle: string;
      redoLabel: string;
      redoTitle: string;
      saveLabel: string;
      saveTitle: string;
      settings: {
        chatLengthWarning: string;
        enableCtrlZ: string;
        maxChatLength: string;
        maxUndoSnapshots: string;
        showSaveButtons: string;
        showToasts: string;
        showUndoButtons: string;
        snapshotEvents: string;
        snapshotEventsDescription: string;
      };
      undoLabel: string;
      undoTitle: string;
    };
  };
  formatting: {
    description: string;
    title: string;
  };
  group: {
    addMember: string;
    allowSelfResponses: string;
    autoMode: string;
    autoModeHint: string;
    clearQueue: string;
    configuration: string;
    forceTalk: string;
    handlingMode: string;
    members: string;
    modes: {
      joinExclude: string;
      joinInclude: string;
      swap: string;
    };
    mute: string;
    peek: string;
    queue: string;
    replyStrategy: string;
    strategies: {
      list: string;
      manual: string;
      natural: string;
      pooled: string;
    };
  };
  instruct: {
    namesBehavior: {
      force: string;
      include: string;
      none: string;
    };
  };
  navbar: {
    aiConfig: string;
    backgrounds: string;
    characterManagement: string;
    chat: string;
    extensions: string;
    personaManagement: string;
    recentChats: string;
    userSettings: string;
    worldInfo: string;
  };
  pagination: {
    first: string;
    last: string;
    next: string;
    perPage: string;
    previous: string;
  };
  persona: {
    createFromCharacter: {
      error: string;
    };
  };
  personaManagement: {
    actions: {
      changeImage: string;
      delete: string;
      duplicate: string;
      rename: string;
      syncName: string;
    };
    activated: string;
    connections: {
      character: string;
      chat: string;
      default: string;
      linkedCharacters: string;
      title: string;
    };
    create: string;
    currentPersona: string;
    default: {
      tooltip: string;
    };
    delete: {
      confirmMessage: string;
      confirmTitle: string;
      error: string;
    };
    description: {
      label: string;
      placeholder: string;
    };
    duplicate: {
      error: string;
    };
    errors: {
      importFailed: string;
      invalidFileFormat: string;
    };
    export: string;
    globalSettings: {
      showNotifications: string;
      title: string;
    };
    import: string;
    lorebooks: {
      label: string;
    };
    noDescription: string;
    rename: {
      prompt: string;
      title: string;
    };
    title: string;
  };
  popup: {
    cropAvatar: {
      title: string;
    };
  };
  secrets: {
    addNewKey: string;
    keyPlaceholder: string;
    keySaved: string;
    labelPlaceholder: string;
    manageKeysFor: string;
    noKeysFound: string;
  };
  settings: {
    chat: {
      stopOnNameHijack: {
        description: string;
        label: string;
        options: {
          all: string;
          group: string;
          none: string;
          single: string;
        };
      };
    };
    powerUser: {
      confirmMessageDelete: {
        description: string;
        label: string;
      };
      neverResizeAvatars: {
        description: string;
        label: string;
      };
      sendOnEnter: {
        description: string;
        label: string;
        options: {
          auto: string;
          disabled: string;
          enabled: string;
        };
      };
      spoilerFreeMode: {
        description: string;
        label: string;
      };
      tagImportSetting: {
        description: string;
        label: string;
        options: {
          all: string;
          ask: string;
          none: string;
          only_existing: string;
        };
      };
      worldImportDialog: {
        description: string;
        label: string;
      };
    };
    ui: {
      chat: {
        forbidExternalMedia: {
          description: string;
          label: string;
        };
        messagesToLoad: {
          description: string;
          label: string;
        };
        reasoningCollapsed: {
          description: string;
          label: string;
        };
      };
      disableAnimations: {
        description: string;
        label: string;
      };
      editor: {
        codeMirrorExpanded: {
          description: string;
          label: string;
        };
        codeMirrorIdentifiers: {
          description: string;
          label: string;
        };
        fields: {
          characterNote: string;
          content: string;
          creatorNotes: string;
          customCss: string;
          description: string;
          dialogueExamples: string;
          editMessage: string;
          firstMessage: string;
          input: string;
          personality: string;
          postHistoryInstructions: string;
          scenario: string;
        };
        groups: {
          character: string;
          chat: string;
          persona: string;
          promptManager: string;
          theme: string;
          worldInfo: string;
        };
      };
    };
  };
  themes: {
    errors: {
      deleteFailed: string;
      importFailed: string;
      loadFailed: string;
      saveFailed: string;
    };
    title: string;
    variables: {
      avatars: {
        borderRadius: string;
        height: string;
        width: string;
      };
      colors: {
        accentGreen: string;
        accentRed: string;
        backgroundTint: string;
        borderColor: string;
        botMessageTint: string;
        chatTint: string;
        emphasisColor: string;
        errorColor: string;
        quoteColor: string;
        shadowColor: string;
        textColor: string;
        underlineColor: string;
        userMessageTint: string;
        warningColor: string;
      };
      layout: {
        panelWidth: string;
        sidebarWidth: string;
      };
      scrollbar: {
        thumbBorderWidth: string;
        thumbColor: string;
        thumbRadius: string;
        thumbShadowColor: string;
        trackColor: string;
        trackRadius: string;
        width: string;
      };
      typography: {
        blurStrength: string;
        borderRadius: string;
        fontFamily: string;
        fontFamilyMono: string;
        fontSize: string;
        shadowWidth: string;
      };
    };
  };
  userSettings: {
    noResults: string;
    searchPlaceholder: string;
  };
  worldInfo: {
    activationSettings: string;
    activeWorlds: string;
    activeWorldsHint: string;
    alertOnOverflow: string;
    alertOnOverflowHint: string;
    budgetCap: string;
    budgetCapHint: string;
    caseSensitive: string;
    caseSensitiveHint: string;
    contextPercent: string;
    deleteBook: string;
    duplicate: string;
    entry: {
      additionalSources: string;
      caseSensitive: string;
      charDescription: string;
      charNote: string;
      charPersonality: string;
      characterFilters: string;
      content: string;
      contentPlaceholder: string;
      creatorNotes: string;
      delay: string;
      delayUntilRecursion: string;
      delete: string;
      depth: string;
      duplicate: string;
      entryState: string;
      entryStates: {
        constant: string;
        normal: string;
      };
      excludeRecursion: string;
      filterCharExclude: string;
      filterCharNames: string;
      filterCharTags: string;
      filterPlaceholder: string;
      group: string;
      groupOverride: string;
      groupSettings: string;
      groupWeight: string;
      ignoreBudget: string;
      keywordsPlaceholder: string;
      logic: string;
      logicOptions: {
        andAll: string;
        andAny: string;
        notAll: string;
        notAny: string;
      };
      matchWholeWords: string;
      move: string;
      order: string;
      outletName: string;
      personaDescription: string;
      positionLabel: string;
      positionOptions: {
        afterAN: string;
        afterChar: string;
        afterEM: string;
        atDepthSystem: string;
        beforeAN: string;
        beforeChar: string;
        beforeEM: string;
        outlet: string;
      };
      positionTooltip: string;
      preventRecursion: string;
      recursionSettings: string;
      scenario: string;
      titlePlaceholder: string;
      toggle: string;
      trigger: string;
    };
    errors: {
      bookNotFound: string;
      createFailed: string;
      deleteFailed: string;
      exportFailed: string;
      importFailed: string;
      loadFailed: string;
      loadListFailed: string;
      renameFailed: string;
      saveFailed: string;
    };
    export: string;
    globalSettings: string;
    import: string;
    importSuccess: string;
    includeNames: string;
    includeNamesHint: string;
    matchWholeWords: string;
    matchWholeWordsHint: string;
    maxRecursionSteps: string;
    maxRecursionStepsHint: string;
    minActivations: string;
    minActivationsDepthMax: string;
    minActivationsDepthMaxHint: string;
    minActivationsHint: string;
    newEntryInBook: string;
    newWorld: string;
    popup: {
      deleteBookContent: string;
      deleteEntryContent: string;
      deleteEntryTitle: string;
      duplicateBookInputSuffix: string;
      duplicateBookTitle: string;
      importEmbeddedContent: string;
      importEmbeddedTitle: string;
      newBookContent: string;
      newBookInput: string;
      newBookTitle: string;
      renameBookTitle: string;
    };
    recursiveScan: string;
    recursiveScanHint: string;
    refresh: string;
    rename: string;
    scanDepth: string;
    searchPlaceholder: string;
    sorting: {
      orderAsc: string;
      title: string;
      titleAsc: string;
      titleDesc: string;
      uidAsc: string;
      uidDesc: string;
    };
    totalActiveTokens: string;
    useGroupScoring: string;
    useGroupScoringHint: string;
  };
}
