import type { AiConfigSection } from './types';

export const aiConfigDefinition: AiConfigSection[] = [
  {
    id: 'presets',
    items: [
      {
        widget: 'preset-manager',
        id: 'api.selectedSampler',
        label: 'aiConfig.presets.sampler.label',
      },
    ],
  },
  {
    id: 'prompt-management',
    items: [
      {
        widget: 'prompt-manager-button',
        label: 'aiConfig.promptManager.label',
        description: 'aiConfig.promptManager.description',
      },
    ],
  },
  {
    id: 'common-settings',
    items: [
      {
        id: 'api.samplers.max_context',
        widget: 'slider',
        label: 'aiConfig.contextSize.label',
        min: 512,
        max: 8192, // Default for older models, will be updated from API
        step: 1,
        maxUnlockedId: 'api.samplers.max_context_unlocked',
        unlockLabel: 'aiConfig.contextSize.unlocked',
        unlockTooltip: 'aiConfig.contextSize.unlockedTooltip',
        conditions: [
          {
            provider: [
              'openai',
              'claude',
              'openrouter',
              'ai21',
              'makersuite',
              'vertexai',
              'mistralai',
              'custom',
              'cohere',
              'perplexity',
              'groq',
              'electronhub',
              'nanogpt',
              'deepseek',
              'aimlapi',
              'xai',
              'pollinations',
              'moonshot',
              'fireworks',
              'cometapi',
              'azure_openai',
              'zai',
              'koboldcpp',
            ],
          },
          {
            provider: 'ollama',
            formatter: 'text',
          },
        ],
      },
      {
        id: 'api.samplers.max_tokens',
        widget: 'number-input',
        label: 'aiConfig.maxResponseLength.label',
        min: 1,
        max: 128000,
        step: 1,
      },
      { widget: 'hr' },
      {
        id: 'api.samplers.stream',
        widget: 'checkbox',
        label: 'aiConfig.streaming.label',
        description: 'aiConfig.streaming.description',
      },
      {
        id: 'api.samplers.show_thoughts',
        widget: 'checkbox',
        label: 'aiConfig.showThoughts.label',
        description: 'aiConfig.showThoughts.description',
        conditions: {
          provider: [
            'claude',
            'deepseek',
            'aimlapi',
            'openrouter',
            'custom',
            'xai',
            'makersuite',
            'vertexai',
            'pollinations',
            'moonshot',
            'mistralai',
            'fireworks',
            'cometapi',
            'electronhub',
            'azure_openai',
            'nanogpt',
            'zai',
            'ollama',
          ],
        },
      },
      {
        id: 'api.samplers.reasoning_effort',
        widget: 'select',
        label: 'aiConfig.reasoningEffort.label',
        infoTooltip: 'aiConfig.reasoningEffort.tooltip',
        infoLink: 'https://docs.sillytavern.app/usage/prompts/reasoning/#reasoning-effort',
        conditions: {
          provider: [
            'openai',
            'custom',
            'claude',
            'xai',
            'makersuite',
            'vertexai',
            'aimlapi',
            'openrouter',
            'pollinations',
            'perplexity',
            'cometapi',
            'electronhub',
            'azure_openai',
            'deepseek',
          ],
        },
        options: [
          { value: 'auto', label: 'aiConfig.reasoningEffort.options.auto' },
          { value: 'min', label: 'aiConfig.reasoningEffort.options.minimum' },
          { value: 'low', label: 'aiConfig.reasoningEffort.options.low' },
          { value: 'medium', label: 'aiConfig.reasoningEffort.options.medium' },
          { value: 'high', label: 'aiConfig.reasoningEffort.options.high' },
          { value: 'max', label: 'aiConfig.reasoningEffort.options.maximum' },
        ],
      },
      {
        widget: 'info-display',
        description: 'aiConfig.reasoningEffort.descriptionOpenAI',
        conditions: {
          provider: ['openai', 'custom', 'xai', 'aimlapi', 'openrouter', 'perplexity', 'electronhub', 'azure_openai'],
        },
      },
      {
        widget: 'info-display',
        description: 'aiConfig.reasoningEffort.descriptionClaude',
        conditions: {
          provider: ['claude'],
        },
      },
      {
        widget: 'info-display',
        description: 'aiConfig.reasoningEffort.descriptionGoogle',
        conditions: {
          provider: ['makersuite', 'vertexai'],
        },
      },
    ],
  },
  {
    id: 'sampling-sliders-1',
    items: [
      {
        id: 'api.samplers.temperature',
        widget: 'slider',
        label: 'aiConfig.temperature.label',
        min: 0,
        max: 2,
        step: 0.01,
      },
      {
        id: 'api.samplers.frequency_penalty',
        widget: 'slider',
        label: 'aiConfig.freqPenalty.label',
        min: -2,
        max: 2,
        step: 0.01,
        conditions: {
          provider: [
            'openai',
            'aimlapi',
            'openrouter',
            'custom',
            'cohere',
            'perplexity',
            'groq',
            'mistralai',
            'electronhub',
            'nanogpt',
            'deepseek',
            'xai',
            'pollinations',
            'moonshot',
            'fireworks',
            'cometapi',
            'azure_openai',
            'koboldcpp',
            'ollama',
          ],
        },
      },
      {
        id: 'api.samplers.presence_penalty',
        widget: 'slider',
        label: 'aiConfig.presPenalty.label',
        min: -2,
        max: 2,
        step: 0.01,
        conditions: {
          provider: [
            'openai',
            'aimlapi',
            'openrouter',
            'custom',
            'cohere',
            'perplexity',
            'groq',
            'mistralai',
            'electronhub',
            'nanogpt',
            'deepseek',
            'xai',
            'pollinations',
            'moonshot',
            'fireworks',
            'cometapi',
            'azure_openai',
            'koboldcpp',
            'ollama',
          ],
        },
      },
      {
        id: 'api.samplers.top_k',
        widget: 'slider',
        label: 'aiConfig.topK.label',
        min: 0,
        max: 500,
        step: 1,
        conditions: [
          {
            provider: [
              'claude',
              'aimlapi',
              'openrouter',
              'makersuite',
              'vertexai',
              'cohere',
              'perplexity',
              'electronhub',
              'koboldcpp',
            ],
          },
          {
            provider: 'ollama',
            formatter: 'text',
          },
        ],
      },
      {
        id: 'api.samplers.top_p',
        widget: 'slider',
        label: 'aiConfig.topP.label',
        min: 0,
        max: 1,
        step: 0.01,
      },
    ],
  },
  {
    id: 'sampling-sliders-2',
    conditions: [{ provider: ['openrouter', 'koboldcpp'] }, { provider: 'ollama', formatter: 'text' }],
    items: [
      {
        id: 'api.samplers.repetition_penalty',
        widget: 'slider',
        label: 'aiConfig.repPenalty.label',
        min: 1,
        max: 2,
        step: 0.01,
      },
      {
        id: 'api.samplers.min_p',
        widget: 'slider',
        label: 'aiConfig.minP.label',
        min: 0,
        max: 1,
        step: 0.001,
      },
      {
        id: 'api.samplers.top_a',
        widget: 'slider',
        label: 'aiConfig.topA.label',
        min: 0,
        max: 1,
        step: 0.001,
        conditions: {
          provider: ['openrouter', 'koboldcpp'],
        },
      },
    ],
  },
  {
    id: 'koboldcpp-settings',
    conditions: { provider: 'koboldcpp' },
    items: [
      { widget: 'header', label: 'aiConfig.koboldcpp.header' },

      // Rep Pen Range
      {
        widget: 'group',
        id: 'koboldcpp_basic',
        label: 'aiConfig.koboldcpp.groups.basic',
        enableable: true,
        items: [
          {
            id: 'api.samplers.providers.koboldcpp.rep_pen_range',
            widget: 'slider',
            label: 'aiConfig.koboldcpp.repPenRange',
            min: 0,
            max: 8192,
            step: 1,
          },
        ],
      },

      // Dynatemp
      {
        widget: 'group',
        id: 'koboldcpp_dynatemp',
        label: 'aiConfig.koboldcpp.groups.dynatemp',
        enableable: true,
        items: [
          {
            id: 'api.samplers.providers.koboldcpp.dynatemp_range',
            widget: 'slider',
            label: 'aiConfig.koboldcpp.dynatempRange',
            min: 0,
            max: 5,
            step: 0.01,
          },
          {
            id: 'api.samplers.providers.koboldcpp.smoothing_factor',
            widget: 'slider',
            label: 'aiConfig.koboldcpp.smoothingFactor',
            min: 0,
            max: 10,
            step: 0.01,
          },
          {
            id: 'api.samplers.providers.koboldcpp.dynatemp_exponent',
            widget: 'slider',
            label: 'aiConfig.koboldcpp.dynatempExponent',
            min: 0,
            max: 10,
            step: 0.01,
          },
        ],
      },

      // Mirostat
      {
        widget: 'group',
        id: 'koboldcpp_mirostat',
        label: 'aiConfig.koboldcpp.groups.mirostat',
        enableable: true,
        items: [
          {
            id: 'api.samplers.providers.koboldcpp.mirostat',
            widget: 'select',
            label: 'aiConfig.koboldcpp.mirostat.label',
            options: [
              { value: 0, label: 'aiConfig.koboldcpp.mirostat.disabled' },
              { value: 1, label: 'aiConfig.koboldcpp.mirostat.v1' },
              { value: 2, label: 'aiConfig.koboldcpp.mirostat.v2' },
            ],
          },
          {
            id: 'api.samplers.providers.koboldcpp.mirostat_tau',
            widget: 'slider',
            label: 'aiConfig.koboldcpp.mirostatTau',
            min: 0,
            max: 10,
            step: 0.01,
          },
          {
            id: 'api.samplers.providers.koboldcpp.mirostat_eta',
            widget: 'slider',
            label: 'aiConfig.koboldcpp.mirostatEta',
            min: 0,
            max: 10,
            step: 0.01,
          },
        ],
      },

      // XTC
      {
        widget: 'group',
        id: 'koboldcpp_xtc',
        label: 'aiConfig.koboldcpp.groups.xtc',
        enableable: true,
        items: [
          {
            id: 'api.samplers.providers.koboldcpp.xtc_threshold',
            widget: 'slider',
            label: 'aiConfig.koboldcpp.xtcThreshold',
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: 'api.samplers.providers.koboldcpp.xtc_probability',
            widget: 'slider',
            label: 'aiConfig.koboldcpp.xtcProbability',
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: 'api.samplers.providers.koboldcpp.nsigma',
            widget: 'slider',
            label: 'aiConfig.koboldcpp.nsigma',
            min: 0,
            max: 10,
            step: 0.01,
          },
        ],
      },

      // DRY
      {
        widget: 'group',
        id: 'koboldcpp_dry',
        label: 'aiConfig.koboldcpp.groups.dry',
        enableable: true,
        items: [
          {
            id: 'api.samplers.providers.koboldcpp.dry_multiplier',
            widget: 'slider',
            label: 'aiConfig.koboldcpp.dryMultiplier',
            min: 0,
            max: 10,
            step: 0.1,
          },
          {
            id: 'api.samplers.providers.koboldcpp.dry_base',
            widget: 'slider',
            label: 'aiConfig.koboldcpp.dryBase',
            min: 0,
            max: 10,
            step: 0.1,
          },
          {
            id: 'api.samplers.providers.koboldcpp.dry_allowed_length',
            widget: 'slider',
            label: 'aiConfig.koboldcpp.dryAllowedLength',
            min: 0,
            max: 100,
            step: 1,
          },
          {
            id: 'api.samplers.providers.koboldcpp.dry_penalty_last_n',
            widget: 'slider',
            label: 'aiConfig.koboldcpp.dryPenaltyLastN',
            min: 0,
            max: 4096,
            step: 1,
          },
          {
            id: 'api.samplers.providers.koboldcpp.dry_sequence_breakers',
            widget: 'textarea',
            label: 'aiConfig.koboldcpp.drySequenceBreakers',
            valueType: 'array',
            arraySeparator: '\n',
          },
        ],
      },

      // TFS
      {
        widget: 'group',
        id: 'koboldcpp_tfs',
        label: 'aiConfig.koboldcpp.groups.tfs',
        enableable: true,
        items: [
          {
            id: 'api.samplers.providers.koboldcpp.tfs',
            widget: 'slider',
            label: 'aiConfig.koboldcpp.tfs',
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: 'api.samplers.providers.koboldcpp.typical',
            widget: 'slider',
            label: 'aiConfig.koboldcpp.typical',
            min: 0,
            max: 1,
            step: 0.01,
          },
        ],
      },

      // Other
      {
        widget: 'group',
        id: 'koboldcpp_grammar',
        label: 'aiConfig.koboldcpp.groups.grammar',
        enableable: true,
        items: [
          {
            id: 'api.samplers.providers.koboldcpp.grammar',
            widget: 'textarea',
            label: 'aiConfig.koboldcpp.grammar',
          },
          {
            id: 'api.samplers.providers.koboldcpp.grammar_retain_state',
            widget: 'checkbox',
            label: 'aiConfig.koboldcpp.grammarRetainState',
          },
          {
            id: 'api.samplers.providers.koboldcpp.banned_tokens',
            widget: 'textarea',
            label: 'aiConfig.koboldcpp.bannedTokens',
            valueType: 'array',
            arraySeparator: '\n',
          },
          {
            id: 'api.samplers.providers.koboldcpp.sampler_order',
            widget: 'draggable-list',
            label: 'aiConfig.koboldcpp.samplerOrder',
            options: [
              { value: 0, label: 'aiConfig.topK.label' },
              { value: 1, label: 'aiConfig.topA.label' },
              { value: 2, label: 'aiConfig.topPMinP' },
              { value: 3, label: 'aiConfig.koboldcpp.groups.tfs' },
              { value: 4, label: 'aiConfig.koboldcpp.typical' },
              { value: 5, label: 'aiConfig.temperature.label' },
              { value: 6, label: 'aiConfig.repPenalty.label' },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'ollama-settings',
    conditions: { provider: 'ollama', formatter: 'text' },
    items: [
      { widget: 'header', label: 'aiConfig.ollama.header' },
      {
        widget: 'group',
        id: 'ollama_advanced',
        label: 'aiConfig.ollama.groups.advanced',
        enableable: true,
        items: [
          {
            id: 'api.samplers.providers.ollama.repeat_last_n',
            widget: 'slider',
            label: 'aiConfig.ollama.repeatLastN',
            min: -1,
            max: 8192,
            step: 1,
          },
          {
            id: 'api.samplers.providers.ollama.num_batch',
            widget: 'number-input',
            label: 'aiConfig.ollama.numBatch',
            min: 1,
            max: 4096,
            step: 1,
          },
          {
            id: 'api.samplers.providers.ollama.num_keep',
            widget: 'number-input',
            label: 'aiConfig.ollama.numKeep',
            min: -1,
            max: 4096,
            step: 1,
          },
          {
            id: 'api.samplers.providers.ollama.tfs_z',
            widget: 'slider',
            label: 'aiConfig.ollama.tfsZ',
            min: 0,
            max: 2,
            step: 0.01,
          },
          {
            id: 'api.samplers.providers.ollama.typical_p',
            widget: 'slider',
            label: 'aiConfig.ollama.typicalP',
            min: 0,
            max: 1,
            step: 0.01,
          },
        ],
      },
    ],
  },
  {
    id: 'provider-specific-settings',
    items: [
      {
        id: 'api.samplers.providers.claude.use_sysprompt',
        widget: 'checkbox',
        label: 'aiConfig.claude.useSysPrompt.label',
        description: 'aiConfig.claude.useSysPrompt.description',
        conditions: { provider: 'claude' },
      },
      {
        id: 'api.samplers.providers.claude.assistant_prefill',
        widget: 'textarea',
        label: 'aiConfig.claude.assistantPrefill.label',
        description: 'aiConfig.claude.assistantPrefill.description',
        conditions: { provider: 'claude' },
      },
      {
        id: 'api.samplers.providers.google.use_makersuite_sysprompt',
        widget: 'checkbox',
        label: 'aiConfig.google.useSysPrompt.label',
        description: 'aiConfig.google.useSysPrompt.description',
        conditions: { provider: ['makersuite', 'vertexai'] },
      },
    ],
  },
];
